/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ecotrack;
import java.util.Comparator;
import java.util.List;
/**
 *
 * @author Justi
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    // Esta es la variable para nuestro "cerebro"
    private SistemaEcoTrack sistema;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        // --- INICIA CÓDIGO A AÑADIR ---

        // 1. Creamos una instancia de nuestro sistema
        this.sistema = new SistemaEcoTrack();

        // 2. Intentamos cargar los datos guardados del archivo
        this.sistema.cargarSistema("residuos.txt");

        // 3. (Opcional) Ponemos un título a la ventana
        this.setTitle("EcoTrack - Sistema de Residuos");
        
        cmbCriterio.addItem("Por Tipo");
        cmbCriterio.addItem("Por Peso");
        cmbCriterio.addItem("Por Prioridad");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtDisplayResiduos = new javax.swing.JTextArea();
        btnActualizar = new javax.swing.JButton();
        cmbCriterio = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtDisplayResiduos.setColumns(20);
        txtDisplayResiduos.setRows(5);
        jScrollPane1.setViewportView(txtDisplayResiduos);

        btnActualizar.setText("Actualizar Lista");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        cmbCriterio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por Tipo", "Por Peso", "Por Prioridad" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizar)
                    .addComponent(cmbCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(cmbCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnActualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        String criterioSeleccionado = (String) cmbCriterio.getSelectedItem();
        
        // 2. Obtenemos el comparador correcto de nuestro "sistema"
        Comparator<Residuo> comparador;
        
        if (criterioSeleccionado.equals("Por Peso")) {
            comparador = sistema.getCompPorPeso();
        } else if (criterioSeleccionado.equals("Por Prioridad")) {
            comparador = sistema.getCompPorPrioridad();
        } else {
            // Por defecto, ordenamos por Tipo
            comparador = sistema.getCompPorTipo();
        }
        
        // 3. Pedimos al sistema la lista ORDENADA
        // (Usando el método que ya creamos en SistemaEcoTrack)
        List<Residuo> listaOrdenada = sistema.getResiduosOrdenados(comparador);
        
        // 4. Limpiamos el área de texto antes de mostrar nuevos datos
        txtDisplayResiduos.setText("");
        
        // 5. Recorremos la lista y la mostramos en el JTextArea
        if (listaOrdenada.isEmpty()) {
            txtDisplayResiduos.setText("No hay residuos registrados.");
        } else {
            // Añadimos un encabezado
            txtDisplayResiduos.append("ID -- NOMBRE -- TIPO -- PESO (Kg) -- PRIORIDAD\n");
            txtDisplayResiduos.append("--------------------------------------------------------------------------\n");

            for (Residuo r : listaOrdenada) {
                // Añadimos una línea de texto por cada residuo
                String linea = r.getId() + " -- " +
                               r.getNombre() + " -- " +
                               r.getTipo() + " -- " +
                               r.getPeso() + " -- " +
                               r.getPrioridadAmbiental() + "\n";
                
                txtDisplayResiduos.append(linea);
            }
        }   
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JComboBox<String> cmbCriterio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDisplayResiduos;
    // End of variables declaration//GEN-END:variables
}
